home/urls.py
from django.urls import path
from .views import HomeView
from . import views
from django.contrib.auth.views import LoginView

app_name='home'

urlpatterns = [
    path('', views.CategoryView.as_view(), name='category'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('category/',views.CategoryView.as_view(), name='category'),
    path('product/<int:product_id>/', views.menu_product_detail, name='menu_product_detail'),
    path('order/',views.OrderView.as_view(), name='order'),
    path('yourorder/',views.YourOrderView.as_view(), name='your_order'),
    path('cart/',views.CartView.as_view(), name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_to_cart_detail/<int:product_id>/', views.add_to_cart_detail, name='add_to_cart_detail'),
    path('add_order/', views.add_order, name='add_order'),
    path('search/', views.search_food, name='search_food'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('profile/', views.update_profile, name='profile'),
    path('cancelled_order/<int:order_id>', views.cancelled_order, name='cancelled_order'),
    path('pay_order/<int:order_id>', views.pay_order, name='pay_order'),
    path('custom_logout/', views.custom_logout, name='custom_logout'),
    path('register/', views.register, name='register'),
    # URL cho quản lý đơn hàng
    path('admin/order/', views.AdminOrderList.as_view(), name='admin_order'),
    path('accept_order/<int:order_id>', views.accept_order, name='admin_accept_order'),
    path('reject_order/<int:order_id>', views.reject_order, name='admin_reject_order'),
    path('delete_order/<int:order_id>', views.delete_order, name='admin_delete_order'),
    # URL cho quản lý thể loại sản phẩm
    path('admin/categories/', views.AdminCategoryList.as_view(), name='admin_category_list'),
    path('delete_categories/', views.delete_categories, name='delete_categories'),
    path('admin/categories/<int:category_id>/', views.admin_category_detail, name='admin_category_detail'),
    path('admin/categories/create/', views.admin_category_create, name='admin_category_create'),
    path('admin/categories/<int:category_id>/update/', views.admin_category_update, name='admin_category_update'),
    # URL cho quản lý sản phẩm
    path('admin/products/', views.AdminProductList.as_view(), name='admin_product_list'),
    path('delete_products/', views.delete_products, name='delete_products'),
    path('delete_promotion/<int:promotion_id>', views.delete_promotion, name='delete_promotion'),
    path('update_promotion/', views.update_promotion, name='update_promotion'),
    path('admin/products/<int:product_id>/', views.admin_product_detail, name='admin_product_detail'),
    path('admin/products/create/', views.admin_product_create, name='admin_product_create'),
    path('admin/products/<int:product_id>/update/', views.admin_product_update, name='admin_product_update'),
    # URL cho quản lý sản phẩm
    path('admin/users/', views.AdminUserList.as_view(), name='admin_user_list'),
    path('delete_users/', views.delete_users, name='delete_users'),
    path('admin/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/users/create/', views.admin_user_create, name='admin_user_create'),
    #URL cho thống kê
    path('admin/statistics/', views.Statistics.as_view(), name='admin_statistics'),  
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('en/', include('home.urls', namespace='en')),
    path('vi/', include('home.urls', namespace='vi')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
)

templates/homepage/base.html
{% load i18n %}
{% load static %}

<!DOCTYPE html>
<html>
<head>
  <!-- Basic -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge" />
  <link rel="shortcut icon" href="{% static 'homepage/images/favicon.png' %}" type="">
  <title> HyNiu Food & Drink </title>
    <!-- bootstrap core css -->
    <link rel="stylesheet" type="text/css" href="{% static 'homepage/css/bootstrap.css' %}" />
    <!-- Custom styles for this template -->
    <link href="{% static 'homepage/css/style.css' %}" rel="stylesheet" />
    
{% block cssblock %}
{% endblock %}

</head>
<body>
  {% block navbarblock %}
  <!-- header section strats -->
  <div class="hero_area">
    {% if request.resolver_match.url_name == 'category' or request.resolver_match.url_name == 'your_order'  or request.resolver_match.url_name == 'menu_product_detail' %}
    <div class="bg-navbar">
      <img src="{% static 'homepage/images/navbar.jpg' %}" alt="">
    </div>
    {% else %}
    <div class="bg-box">
      <img src="{% static 'homepage/images/bground.jpg' %}" alt="">
    </div>
    {% endif %}
  <header class="header_section">
      <div>
        <nav class="navbar navbar-expand-lg custom_nav container ">
          <a class="navbar-brand" href="{% url 'home:home' %}">
            <span>
              HyNiu F&D
            </span>
          </a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class=""> </span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav  mx-auto ">
              <li class="listlink"><a href="{% url 'home:home' %}"> {% trans "HOME" %}</a> </li>
              <li class="listlink"><a href="{% url 'home:category' %}">&emsp;  &emsp; {% trans "MENU" %}</a></li>
              <li class="listlink"><a href="https://www.facebook.com/emiotsetsubun">&emsp;  &emsp; {% trans "ABOUT" %}</a></li>
            </ul>
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% if request.resolver_match.url_name == 'home' or request.resolver_match.url_name == 'index' %}
            <a class="listlink" href="{% url 'vi:home' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:home' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:home' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:home' %}" class="trans-button"> EN &emsp; </a> 
            {% elif request.resolver_match.url_name == 'login' %}
            <a class="listlink" href="{% url 'vi:login' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:login' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:login' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:login' %}" class="trans-button"> EN &emsp; </a>
            {% elif request.resolver_match.url_name == 'category' %}
            <a class="listlink" href="{% url 'vi:category' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:category' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:category' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:category' %}" class="trans-button"> EN &emsp; </a>
            {% elif request.resolver_match.url_name == 'profile' %}
            <a class="listlink" href="{% url 'vi:profile' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:profile' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:profile' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:profile' %}" class="trans-button"> EN &emsp; </a>
            {% elif request.resolver_match.url_name == 'register' %}
            <a class="listlink" href="{% url 'vi:register' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:register' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:register' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:register' %}" class="trans-button"> EN &emsp; </a>
            {% elif request.resolver_match.url_name == 'cart' %}
            <a class="listlink" href="{% url 'vi:cart' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:cart' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:cart' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:cart' %}" class="trans-button"> EN &emsp; </a>  
            {% elif request.resolver_match.url_name == 'order' %}
            <a class="listlink" href="{% url 'vi:order' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:order' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:order' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:order' %}" class="trans-button"> EN &emsp; </a>    
            {% elif request.resolver_match.url_name == 'your_order' %}
            <a class="listlink" href="{% url 'vi:your_order' %}">  &emsp;
              <img src="/static/homepage/images/vi.png" class="imagesflag">
              <a  href="{% url 'vi:your_order' %}" class="trans-button"> VI </a> 
            <a class="listlink" href="{% url 'en:your_order' %}">   &emsp;
              <img src="/static/homepage/images/en.png" class="imagesflag">
              <a  href="{% url 'en:your_order' %}" class="trans-button"> EN &emsp; </a>    
              {% elif request.resolver_match.url_name == 'menu_product_detail' %}
              <a class="listlink" href="{% url 'vi:menu_product_detail' product_id=product.id %}">  &emsp;
                <img src="/static/homepage/images/vi.png" class="imagesflag">
                <a  href="{% url 'vi:menu_product_detail' product_id=product.id %}" class="trans-button"> VI </a> 
              <a class="listlink" href="{% url 'en:menu_product_detail' product_id=product.id %}">   &emsp;
                <img src="/static/homepage/images/en.png" class="imagesflag">
                <a  href="{% url 'en:menu_product_detail' product_id=product.id %}" class="trans-button"> EN &emsp; </a>    
            {% endif %}
            <div class="user_option">
              {% if user.is_authenticated %}
              <a href="{% url 'home:profile' %}" class="user_link">
                {{ user.get_username }}
                <i class="fa fa-user" aria-hidden="true"></i>
              </a>
              {% else %}
              <a href="{% url 'login' %}" class="user_link">
                {%trans "Login"%}
                <i class="fa fa-user" aria-hidden="true"></i>
              </a>
              {% endif %}
              {% if user.is_authenticated %}
              <a href="{% url 'home:cart' %}" class="user_link">
                <i class="fa fa-shopping-cart	" aria-hidden="true">({{total_quantity}})</i>
              </a>
              {% elif user.order %}
              <a href="{% url 'home:yourorder' %}" class="user_link">
                <i class="fa fa-shopping-cart	" aria-hidden="true"></i>
              </a>
              {% endif %}
              {% if user.is_staff %}
                <a href="{% url 'home:admin_order' %}" class="sunas"> <b>{%trans "Admin Page"%}</b></a>
              {% else %}
                <a href="https://sun-asterisk.vn/en/" class="sunas"> <b> Sun Asterisk</b></a>
              {% endif %}
            </div>
          </div>
        </nav>
      </div>
  </header>
  <!-- end header section -->
  {% endblock %}

  {% block content %}
  {% endblock %}
  {% if request.resolver_match.url_name == 'your_order' %}
  {% else %}
  {% include 'homepage/footer.html' %}
  {% endif %}
</div>
<!-- jQery -->
<script src="{% static 'homepage/js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'homepage/js/chart.js' %}"></script>
<script src="{% static 'homepage/js/total.js' %}"></script>
<script src="{% static 'homepage/js/order_list.js' %}"></script>
</body>
</html>

templates/homepage/footer.html
{% load i18n %}
{% load static %}

  <!-- footer section -->
  <link href="{% static 'homepage/css/font-awesome.min.css'%}" rel="stylesheet" />
  <footer class="footer_section">
    <div class="container">
      <div class="row">
        <div class="col-md-4 footer-col">
          <div class="footer_contact">
            <h4>  {% trans " Contact Us "%} </h4>
            <div class="contact_link_box">
              <a>
                <i class="fa fa-phone" aria-hidden="true"></i>   <!-- Add symbol -->
                <span> {%trans "Call Liu: +84 394188326"%} </span>
              </a>
              <a>
                <i class="fa fa-phone" aria-hidden="true"></i>   <!-- Add symbol -->
                <span> {%trans "Call Huy: +84 343036100"%} </span>
              </a>
              <a>
                <i class="fa fa-envelope" aria-hidden="true"></i>  <!-- Add symbol -->
                <span> doanquangluu2002.nha@gmail.com </span>
              </a>
              <a>
                <i class="fa fa-envelope" aria-hidden="true"></i>  <!-- Add symbol -->
                <span>leekanghye2002@gmail.com </span>
              </a>

            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <div class="footer_detail">
            <a href="" class="footer-logo"> HyNiu </a>
            <p> {% trans " The most important thing is always the customer's taste and the reliability of the food "%} </p>
            <p>{% trans " We are honored to serve you "%}</p>
            <div class="footer_social">
              <a href="https://www.facebook.com/mobeo2002/">
                <i class="fa fa-facebook" aria-hidden="true"></i>
              </a>
              <a href="https://twitter.com/onQuangLu1">
                <i class="fa fa-twitter" aria-hidden="true"></i>
              </a>
              <a href="https://www.instagram.com/_wang_liuu.cute/">
                <i class="fa fa-instagram" aria-hidden="true"></i>
              </a>
              <a href="https://www.youtube.com/channel/UC4rbqOMxaMCT-Nozz1or1kQ">
                <i class="fa fa-youtube" aria-hidden="true"></i>
              </a>
              <a href="https://github.com/holy36">
                <i class="fa fa-github" aria-hidden="true"></i>
              </a>
            </div>
          </div>
        </div>
        <div class="col-md-4 footer-col">
          <h4>
            {% trans " Opening Hours "%}
          </h4>
          <p>
            {% trans " Everyday "%}
          </p>
          <p>
            8.00 Am -10.00 Pm
          </p>
        </div>
      </div>
    </div>
  </footer>
  <!-- footer section -->

templates/homepage/index.html
{% extends 'homepage/base.html'%}
{% load static %}
{% load i18n %}

{% block content %}
    <!-- Header section -->
    <!-- slider section -->
    <section class="slider_section ">
            <div class="container ">
                <div class="col-md-7 col-lg-6 ">
                  <div class="title">
                    <h1> HyNiu Food & Drink </h1>
                    <p> {% trans " We are Hyniu restaurant, managed by Le Quang Huy and Doan Quang Liu with a chain of 507 stores worldwide."%} </p>
                    <p> {% trans "Welcome to Hyniu Food & Drink! "%} </p>
                  </div>
                </div>
            </div>
    </section>
    <!-- end slider section -->
  </div>
    <!-- Footer section-->
{% endblock %}