home/urls.py
from django.urls import path
from .views import HomeView
from . import views
from django.contrib.auth.views import LoginView

app_name='home'

urlpatterns = [
    path('', views.CategoryView.as_view(), name='category'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('category/',views.CategoryView.as_view(), name='category'),
    path('product/<int:product_id>/', views.menu_product_detail, name='menu_product_detail'),
    path('order/',views.OrderView.as_view(), name='order'),
    path('yourorder/',views.YourOrderView.as_view(), name='your_order'),
    path('cart/',views.CartView.as_view(), name='cart'),
    path('add_to_cart/<int:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('add_to_cart_detail/<int:product_id>/', views.add_to_cart_detail, name='add_to_cart_detail'),
    path('add_order/', views.add_order, name='add_order'),
    path('search/', views.search_food, name='search_food'),
    path('update_cart/', views.update_cart, name='update_cart'),
    path('accounts/login/', LoginView.as_view(), name='login'),
    path('profile/', views.update_profile, name='profile'),
    path('cancelled_order/<int:order_id>', views.cancelled_order, name='cancelled_order'),
    path('pay_order/<int:order_id>', views.pay_order, name='pay_order'),
    path('custom_logout/', views.custom_logout, name='custom_logout'),
    path('register/', views.register, name='register'),
    # URL cho quản lý đơn hàng
    path('admin/order/', views.AdminOrderList.as_view(), name='admin_order'),
    path('accept_order/<int:order_id>', views.accept_order, name='admin_accept_order'),
    path('reject_order/<int:order_id>', views.reject_order, name='admin_reject_order'),
    path('delete_order/<int:order_id>', views.delete_order, name='admin_delete_order'),
    # URL cho quản lý thể loại sản phẩm
    path('admin/categories/', views.AdminCategoryList.as_view(), name='admin_category_list'),
    path('delete_categories/', views.delete_categories, name='delete_categories'),
    path('admin/categories/<int:category_id>/', views.admin_category_detail, name='admin_category_detail'),
    path('admin/categories/create/', views.admin_category_create, name='admin_category_create'),
    path('admin/categories/<int:category_id>/update/', views.admin_category_update, name='admin_category_update'),
    # URL cho quản lý sản phẩm
    path('admin/products/', views.AdminProductList.as_view(), name='admin_product_list'),
    path('delete_products/', views.delete_products, name='delete_products'),
    path('delete_promotion/<int:promotion_id>', views.delete_promotion, name='delete_promotion'),
    path('update_promotion/', views.update_promotion, name='update_promotion'),
    path('admin/products/<int:product_id>/', views.admin_product_detail, name='admin_product_detail'),
    path('admin/products/create/', views.admin_product_create, name='admin_product_create'),
    path('admin/products/<int:product_id>/update/', views.admin_product_update, name='admin_product_update'),
    # URL cho quản lý sản phẩm
    path('admin/users/', views.AdminUserList.as_view(), name='admin_user_list'),
    path('delete_users/', views.delete_users, name='delete_users'),
    path('admin/users/<int:user_id>/', views.admin_user_detail, name='admin_user_detail'),
    path('admin/users/create/', views.admin_user_create, name='admin_user_create'),
    #URL cho thống kê
    path('admin/statistics/', views.Statistics.as_view(), name='admin_statistics'),  
]

shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import RedirectView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('en/', include('home.urls', namespace='en')),
    path('vi/', include('home.urls', namespace='vi')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += i18n_patterns(
    path('home/', include('home.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
)

home/models.py
from django.db import models
from datetime import datetime
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.utils.translation import gettext_lazy as _
from django.utils import timezone
from django.core.validators import MaxValueValidator, MinValueValidator

class CustomUser(AbstractUser):
    phone = models.CharField(max_length=15)
    address = models.CharField(max_length=255)

    def get_user_orders(self): #trả về các đơn hàng của người dùng cụ thể
        return self.order_set.all()

class Category(models.Model):
    name = models.CharField(max_length=50)
    parent = models.ForeignKey('self', on_delete=models.SET_NULL, null=True, blank=True, help_text=_("Parent category of this category (if any)."))

    def __str__(self):
        return self.name

class Product(models.Model):
    name = models.CharField(max_length=50)
    image = models.ImageField(upload_to='product_images/', default='homepage/image404.png', null=True, blank=True, help_text=_("Product image"))
    description = models.CharField(max_length=255, help_text=_("Brief description of the product."))
    base_price = models.DecimalField(max_digits=12, decimal_places=0, help_text=_("The origin price of the product."))
    number_in_stock = models.IntegerField(default=0, help_text=_("Quantity of the product available in stock."))
    sold_number = models.IntegerField(default=0, help_text=_("Number of products sold."))
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True, blank=True)

    def __str__(self):
        return self.name

    def is_available(self):
        return self.number_in_stock > 0

    def get_stock_count(self):
        return self.number_in_stock
    
    class Meta:
        ordering = ['name']

        def __str__(self):
            return self.name

class Order(models.Model):
    order_date = models.DateTimeField(default=timezone.now, help_text=_("Date of the order."))
    ORDER_STATUS = (
        (0, 'Pending'),
        (1, 'Ongoing'),
        (2, 'Cancelled'),
        (3, 'Rejected'),
        (4, 'Completed'),
    )
    status = models.IntegerField(choices=ORDER_STATUS, default=0, help_text=_("Status of the order."))
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    cart = models.ForeignKey('Cart', on_delete=models.CASCADE)
    order_cost = models.DecimalField(max_digits=12, decimal_places=0, default=0, help_text=_("total cost of order."))

class OrderDetail(models.Model):
    price = models.DecimalField(max_digits=12, decimal_places=0, default=0, help_text=_("Price of product at order."))
    quantity = models.IntegerField(default=0, help_text=_("total quantity of products ordered."))
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    total_cost = models.DecimalField(max_digits=12, decimal_places=0, default=0, help_text=_("total cost of order."))

class Cart(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

class CartItem(models.Model):
    quantity = models.IntegerField(default=1, help_text=_("Quantity of each product in the cart."))
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

class BestSeller(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    sold_number = models.IntegerField(default=0, help_text=_("The number of sales of the best-selling product."))

    class Meta:
        verbose_name = _("Best Seller")
        verbose_name_plural = _("Best Sellers")

class Promotion(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    description = models.CharField(max_length=255, help_text=_("Brief description of the promotion."))
    dis_percent = models.IntegerField(default=0)
    start_date = models.DateTimeField(default=timezone.now)
    end_date = models.DateTimeField(default=timezone.now)

class Review(models.Model):
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    rating = models.IntegerField(
        validators=[MinValueValidator(1), MaxValueValidator(5)]
    )
    comment = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Review by {self.user.username} for {self.product.name}"

templates/catalog/cart.html
{% extends 'homepage/base.html'%}
{% load i18n %}
{% load static %}
{%load djmoney%}
{% money_localize money on}

{% block content %}

  <!-- slider section -->
    <section class="slider_section ">
            <div class="container ">
                <div class="cart-container">
                    <h1 class="total-text">{% trans "SHOPPING CART" %} </h1>
                    <a  href="{% url 'home:your_order' %}"  class="ordercart" > {% trans "YOUR ORDERS" %} </a>
                    <br>
                  <table class="tablecart">
                      <thead>
                          <tr>
                            <th>{% trans "Product Name" %}</th>
                            <th>{% trans "Price" %}</th>
                            <th>{% trans "Quantity" %}</th>
                            <th>{% trans "Action" %}</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for cart in cartall %}
                          <tr id="row_{{cart.cart.id}}" data-url="{% url 'home:update_cart'  %}" data-csrf="{{ csrf_token }}">
                            <td>{% trans cart.product.name %}</td>
                            <td>{% if cart.promotion > 0 %}
                              <h6 class="text-danger"> <del>{% money_localize cart.product.base_price 'VND' %} </del></h6>
                              <h6> {% money_localize cart.promotion 'VND' %} </h6>
                            {% else %}
                              <h6> {% money_localize cart.product.base_price 'VND' %} </h6>
                            {% endif %}</td>
                              <td>
                                <div>
                                    {% csrf_token %}
                                    <button onclick="action('{{cart.cart.id}}', 'decrease')">-</button>
                                    <span id="quantity_{{cart.cart.id}}">{{cart.cart.quantity}}</span>
                                    <button  onclick="action('{{cart.cart.id}}', 'increase')">+</button>
                                </div>
                            </td>
                            <td>
                                <div>
                                    {% csrf_token %}
                                    <button  onclick="action('{{cart.cart.id}}', 'delete')">{% trans "Delete" %}</button>
                                </div>
                            </td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>        
                  <div>         
                    <h1 class="d-inline">{% trans "Total" %}: </h1><h1 class="d-inline" id="total_price">{% money_localize total_price 'VND' %}</h1>
                  </div> 
                  {% if cartall %}
                  <a href="{% url 'home:order' %}" class="ordercart">{% trans "Order" %}</a>
                  {% else %}
                  <a href="{% url 'home:cart' %}" onclick="alert('{% trans "There are no products in your cart, please add products to cart!!!" %}')" class="ordercart">Order</a>
                  {% endif %}
                </div>   
            </div>
    </section>
  <!-- end slider section -->
</div>
{% endblock %}

templates/catalog/menu.html
{% extends 'homepage/base.html'%}
{% load i18n %}
{% load static %}
{%load djmoney%}
{% money_localize money on %}

{% block content %}
<section class="food_section layout_padding-bottom">
    <div class="container">
      <div class="heading_container heading_center">
        <h2>
         {%trans "Our Menu" %} </h2> <br>
         <h3>
         <form method="GET" class="d-inline">
          {%trans "Search: " %}
          <input class="input-search" placeholder='{% trans "Search for food here" %}' name="food_name" type="text" />
          <button type="submit" class="fa fa-search searchbox" aria-hidden="true" >
          </button> 
        </form> &emsp;
        <form method="get" class="d-inline">
          <label class="d-inline" for="filter"  >{%trans "Filter:" %} </label>
          <select id="filter_menu" name="filter_menu" class="input-search">
              <option value="all">{%trans "All" %}</option>
              <option value="by_sold_number">{%trans "By Sold Number" %}</option>
              <option value="by_promotion">{%trans "By Promotion" %}</option>
          </select>
          <button type="submit" class="fa fa-search searchbox" aria-hidden="true" >
          </button> 
      </form>
        </h3>
      </div>
      <ul class="filters_menu">
        {% for Category in menu %}
            <li class="active" data-filter=".{{ Category.name }}">
                <a href="?category={{Category.name}}">  {% trans Category.name %} </a>
            </li>
            &emsp; 
        {% endfor %}
    </ul>
    <div class="filters-content">
      <div class="row grid">
        {% for Product in products_array%}
        {% if request.GET.category == Product.product.category.name or request.GET.category|length == 0  %}
        <div class="col-sm-6 col-lg-4 all pizza">
          <div class="box">
            <div>
              <div class="img-box">
                <img src="{{Product.product.image.url}}" >
              </div>
              <div class="detail-box">
                <h5  class="product-title-text"> {% trans Product.product.name%}</h5>
                <p class="description-text"> {% trans Product.product.description %} </p>
                <h6 class="font-weight-bold d-inline">{%trans "Sold:"%} {{Product.product.sold_number}}  &emsp;  &emsp;  &emsp;  </h6>    
                  &emsp; &emsp; &emsp; <a href="{% url 'home:menu_product_detail' Product.product.id %}" class="product-link text-primary d-inline">{%trans "View More" %}</a>
                <div class="options"> 
                  {% if Product.promotion > 0 %}
                    <h6 class="text-danger"> <del>{% money_localize Product.product.base_price 'VND' %} </del></h6>
                    <h6> {% money_localize Product.promotion 'VND' %} </h6>
                  {% else %}
                    <h6> {% money_localize Product.product.base_price 'VND' %} </h6>
                  {% endif %}
                  {% if Product.cart_item_quantity %}
                  <a href="{% url 'home:add_to_cart' Product.product.id %}" class="user_link bg-success">
                    <i class="fa fa-shopping-cart	" aria-hidden="true"></i>  ({{Product.cart_item_quantity}})
                  </a>
                  {% else %}
                    <a href="{% url 'home:add_to_cart' Product.product.id %}" class="user_link">
                      <i class="fa fa-shopping-cart	" aria-hidden="true"></i>
                    </a>
                  {% endif %}
                </div>
              </div>
            </div>
          </div>
        </div>
        {% endif %}
        {% empty %}
          <h2>{% trans "There are no products matching the search results!!!" %}</h2>
        {% endfor %}
      </div>
    </div>
    </div>
</section>
{% endblock %}>

templates/catalog/order.html
{% extends 'homepage/base.html'%}
{% load i18n %}
{% load static %}
{%load djmoney%}
{% money_localize money on}

{% block content %}

  <!-- slider section -->
    <section class="slider_section ">
            <div class="container ">
                <div class="cart-container">
                    <h1>{% trans "YOUR ORDER" %}</h1>
                    <br>
                  <table class="tablecart">
                      <thead>
                          <tr>
                            <th>{% trans "Product Name" %}</th>
                            <th>{% trans "Price" %}</th>
                            <th>{% trans "Quantity" %}</th>
                          </tr>
                      </thead>
                      <tbody>
                          {% for cart in cartall %}
                          <tr id="row_{{cart.id}}" data-url="{% url 'home:update_cart'  %}" data-csrf="{{ csrf_token }}">
                            <td>{% trans cart.product.name %}</td>
                            <td>{% if cart.promotion > 0 %}
                              <h6 class="text-danger"> <del>{% money_localize cart.product.base_price 'VND' %} </del></h6>
                              <h6> {% money_localize cart.promotion 'VND' %} </h6>
                            {% else %}
                              <h6> {% money_localize cart.product.base_price 'VND' %} </h6>
                            {% endif %}</td>
                            <td>{{ cart.quantity }}</td>
                          </tr>
                          {% endfor %}
                      </tbody>
                  </table>        
                  <div>         
                    <h1 class="total-text">{% trans "Total" %}: </h1><h1 class="total-text" id="total_price">{% money_localize total_price 'VND' %}</h1>
                  </div> 
                  <ul class="infor">                 
                     <h1>{% trans "User's Information:" %} </h1>
                     <li>{% if user.first_name or user.last_name %}
                        <p>{% trans "Name:" %} {{user.first_name}} {{user.last_name}}</p>
                    {% else %}
                        <p class="errororder">{% trans "Please enter your name." %}</p>
                    {% endif %}</li>
                     <li>{% if user.phone %}
                        <p>{% trans "User's Phone Number:" %} {{ user.phone }}</p>
                    {% else %}
                        <p class="errororder">{% trans "Please enter your phone number." %}</p>
                    {% endif %}</li>
                    <li>{% if user.address %}
                        <p>{% trans "User's Address:" %} {{ user.address }}</p>
                    {% else %}
                        <p class="errororder">{% trans "Please enter your address." %}</p>
                    {% endif %}</li>
                    <li><p>{% trans "User's Email:" %} {{user.email}}</p></li>
                  </ul>
                  {% if user.first_name or user.last_name or user.phone or user.address%}
                    <a onclick="alert('{% trans "Your order is being approved by admin, please wait a little longer!" %}')" href="{% url 'home:add_order' %}" class="ordercart">{% trans "Order" %}</a>
                  {% else %}
                    <a onclick="alert('{% trans "Your information is incomplete, please update all information before ordering!!!" %}')" class="ordercart">{% trans "Order" %}</a>
                    {% endif %}
                  <div>         
                  </div> 
                </div>   
            </div>
    </section>
  <!-- end slider section -->
</div>
{% endblock %}

templates/catalog/product_detail.html
{% extends 'homepage/base.html'%}
{% load i18n %}
{% load static %}
{%load djmoney%}
{% money_localize money on %}

{% block content %}
<section class="product-detail">
    <div class="container">
        <div class="row">
            <div class="col-md-6">
                <img src="{{ product.image.url }}" alt="{{ product.name }}" class="menu-product-detail-image">
            </div>
            <div class="col-md-6">
                <h1 class="text-dark">{% trans product.name %}</h1>
                <h5 class="text-dark">{% trans product.description %}</h5>
                <p class="text-dark font-weight-bold">{% trans "Sold" %}: {{ product.sold_number }}</p>
                <div class="text-dark">
                    {% trans "Price: " %}
                    {% if promotion_status > 0 %}
                        <span class="text-danger"><del>{% money_localize product.base_price 'VND' %}</del></span>  &emsp;
                        <span class="text-dark">{% money_localize promo_price 'VND' %}</span>
                    {% else %}
                        <span class="text-dark">{% money_localize product.base_price 'VND' %}</span>
                    {% endif %}
                </div> <br>
                <form method="post" action="{% url 'home:add_to_cart_detail' product.id %}">
                <div id="dataa"  data-url="{% url 'home:update_cart'  %}" data-csrf="{{ csrf_token }}">
                    {% csrf_token %} 
                        <input type="number" name="quantity" min=1 id="quantity_{{cart.id}}" class="number-product-detail" ></input> <p class="font-weight-bold text-dark"> <br>Number In Cart: {{cart_item_quantity}}</p>
                </div> <br>

                <button type="submit" href="{% url 'home:add_to_cart_detail' product.id %}" class="btn btn-primary add-to-cart bg-warning">
                    <i class="fa fa-shopping-cart " aria-hidden="true"></i> {% trans "Add to Cart" %}
                </button>
            </form>
    <br>
</div>
<div class="div-review">
{% if request.user.is_authenticated %}
<br> <br> <br>
<div class="add-review review-review">
    <h3>{% trans "Add a Review" %}</h3>
    <form method="post" action="" class="review-form">
        {% csrf_token %}
        
        <div class="form-group">
            <label for="{{ review_form.rating.id_for_label }}">{% trans "Rating:" %} &emsp;</label>
            <input class="border-rating" type="number" name="{{ review_form.rating.name }}" id="{{ review_form.rating.id_for_label }}"
            min="1" max="5" step="1" required>        </div>
        <div class="form-group">
            <label for="{{ review_form.comment.id_for_label }}">{% trans "Review:" %} &emsp;</label>
            {{ review_form.comment }}
        </div>

        <button type="submit" class="submit-button">{% trans "Submit Review" %}</button>
    </form>
</div>
        {% else %}
        <br> <br> <br>
        <div class="add-review review-review">
            <h3>{% trans "Add a Review" %}</h3>
            <form method="post" action="" class="review-form">
                {% csrf_token %}
                <div class="form-group">
                    <label>{% trans "Rating:" %} &emsp;</label>
                    <input class="border-rating" type="number" name="{{ review_form.rating.name }}" id="{{ review_form.rating.id_for_label }}"
                    min="1" max="5" step="1" required>        </div>
                <div class="form-group">
                    <label>{% trans "Review:" %} &emsp;</label>
                    <input class="border-rating" type="text" placeholder='{% trans "Login To Add Review" %}'>
                </div>
        
                <a href="{% url 'login' %}" class="submit-button searchbox">{% trans "Submit Review" %}</a>
            </form>
        </div>
        {% endif %}
        
        <div class="product-reviews float-right view-review">
           <h3>{% trans "Product Reviews" %}</h3>
            <ul >
                {% for review in reviews %}
                    <li class="review-item">
                        <div class="review-header fa fa-user-circle-o">
                            <strong>{{ review.user.username }}:</strong>
                            <span class="rating font-italic">{% trans "Rating:" %} {{ review.rating }}/5</span>
                        </div>
                        <div class="review-comment">{% trans "Review:" %} {{ review.comment }}</div>
                    </li>
                {% empty %}
                    <li class="no-reviews">{% trans "No reviews yet." %}</li>
                {% endfor %}
            </ul>
        </div>
</div>
</div>
    </div>
</section>
{% endblock %}

templates/catalog/yourorder.html
{% extends 'homepage/base.html'%}
{% load i18n %}
{% load static %}
{%load djmoney%}
{% money_localize money on}

{% block content %}
<div class="orderlist-container">
    <div class="filter-sidebar">
        <!-- Thêm bộ lọc ở đây -->
        <h2>{%trans "Filter" %}</h2>
    
        <div class="filter-item">
            <label for="start-date">{%trans "Start Date" %}:</label>
            <input type="text" class="filter-date" id="start-date" pattern="\d{2}/\d{2}/\d{4}" placeholder="dd/mm/yyyy">
        </div>
        
        <div class="filter-item">
            <label for="end-date">{%trans "End Date" %}:</label>
            <input type="text" class="filter-date" id="end-date" pattern="\d{2}/\d{2}/\d{4}" placeholder="dd/mm/yyyy">
        </div>
    
        <div class="filter-item">
            <label for="price-filter">{%trans "Price Range" %}:</label>
            <input type="number" class="filter-price" id="min-price" placeholder="{% trans 'Min price' %}">
            <input type="number" class="filter-price" id="max-price" placeholder="{% trans 'Max price' %}">
        </div>
    
        <div class="filter-buttons">
            <button id="refresh-filter">{%trans "Refresh" %}</button>
            <button id="apply-filter">{%trans "Apply" %}</button>
        </div>
    </div>

    <div class="order-list">
        <span>
            <div class="orderlist-navbar">
                <a href="?status=all">{%trans "All" %}</a>
                <a href="?status=pending">{%trans "Pending" %}</a>
                <a href="?status=accepted">{%trans "Ongoing" %}</a>
                <a href="?status=cancelled">{%trans "Cancelled" %}</a>
                <a href="?status=rejected">{%trans "Rejected" %}</a>
                <a href="?status=completed">{%trans "Completed" %}</a>
            </div>
        </span>
        {% for orderAll in orderAllItem %}
            {% if request.GET.status == 'all' or orderAll.order.get_status_display|lower == request.GET.status|lower %}
            <div class="order-details">
                <div class="line-container big-text">
                    <span class="left">{%trans "Customer" %}: {{ orderAll.order.user.first_name }} {{ orderAll.order.user.last_name }}</span>
                    <span class="right">{%trans "Status" %}: {% trans orderAll.order.get_status_display %}</span>
                </div>
            
                <table class="table-orderdetail">
                    {% for order_detail in orderAll.allItem %}
                    <tr>
                        <td class="image-cell"><img src="{{ order_detail.product.image.url }}" alt="{{ order_detail.product.name }}"></td>
                        <td>{{ order_detail.product.name }}</td>
                        <td>x{{ order_detail.quantity }}</td>
                        <td>{% money_localize order_detail.price 'VND' %}</td>
                    </tr>
                    {% endfor %}
                </table>
            
                <div class="line-container big-text">
                    <span class="cus-left" data-formatted-date="{{ orderAll.formatted_date }}">{%trans "Order Date" %}: {{ orderAll.formatted_date }}</span>
                    <span class="cus-right" data-total-price="{{ orderAll.total_price }}">{%trans "Total Cost" %}: {% money_localize orderAll.total_price 'VND' %}</span>
                </div>

                {% if orderAll.order.status == 1 %}
                <div class="pay-btn">
                    <a href="{% url 'home:pay_order' orderAll.order.id %}" class="btn btn-success">{% trans "Pay" %}</a>  
                </div>
                {% endif %}

            </div>
            {% endif %}
        {% endfor %}
    </div>
</div>
{% endblock %}